#!/usr/bin/env python3
"""
run_machine.py — one pulse of "the machine".

Runs the audit + the optimizer, assembles a single combined feed, and writes it
to docs/ so a live dashboard (ours on GitHub Pages, or the Manus site fetching the
raw URL) can poll it. Optionally commits + pushes the feed so the change is live.

This is the unit you schedule. Every run refreshes docs/feed.json; the dashboard
polls that file and re-renders — so the site live-monitors the machine.

Feed schema (docs/feed.json):
    { generated_at, source, audit{...}, optimizer{...}, community{...} }

⚠️ PRIVACY: the feed contains rule IDs, edges, and stakes. Publishing it to a
PUBLIC repo exposes your operation. Default targets sample data. Only point
--configs/--bets at real live/ + data/ if the publish target is PRIVATE
(see ORCHESTRATION.md §6).

Usage:
    python run_machine.py                                   # sample data -> docs/feed.json
    python run_machine.py --configs live/ --bets data/x.csv # real (private targets only)
    python run_machine.py --publish                         # also git commit+push docs/feed.*
"""
from __future__ import annotations
import argparse
import json
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent
AUDIT = REPO / "audit" / "audit_configs.py"
OPTIMIZE = REPO / "optimizer" / "optimize.py"

HEADLINE = {
    "self_reference": "Self-Ref Violations",
    "j_mo_no_differentiation": "Stack Collisions",
    "duplicate_id": "Duplicate Rule IDs",
    "duplicate_id_in_file": "Duplicate Rule IDs",
}


def run_json(cmd: list[str]) -> tuple[dict, int]:
    p = subprocess.run(cmd, capture_output=True, text=True)
    if not p.stdout.strip():
        sys.stderr.write(p.stderr)
        raise SystemExit(f"no JSON from: {' '.join(cmd)} (exit {p.returncode})")
    return json.loads(p.stdout), p.returncode


def get_audit(config_dir: str) -> dict:
    audit, _ = run_json([sys.executable, str(AUDIT), "--dir", config_dir, "--format", "json"])
    counts = audit.get("counts_by_check", {})
    cards = {label: 0 for label in dict.fromkeys(HEADLINE.values())}
    for check, label in HEADLINE.items():
        cards[label] += counts.get(check, 0)
    audit["cards"] = cards
    return audit


def get_optimizer(config_dir: str, bets: str, bankroll: float) -> dict | None:
    if not Path(bets).exists():
        return None
    with tempfile.TemporaryDirectory() as td:
        out = str(Path(td) / "proposals.json")
        subprocess.run([sys.executable, str(OPTIMIZE), "--bets", bets,
                        "--configs", config_dir, "--bankroll", str(bankroll), "--out", out],
                       capture_output=True, text=True)
        return json.loads(Path(out).read_text())


def main():
    ap = argparse.ArgumentParser(description="Run the machine and emit the live dashboard feed")
    ap.add_argument("--configs", default="configs/sample_live")
    ap.add_argument("--bets", default="optimizer/sample_bets.csv")
    ap.add_argument("--bankroll", type=float, default=10000.0)
    ap.add_argument("--out-dir", default=str(REPO / "docs"))
    ap.add_argument("--publish", action="store_true", help="git add+commit+push the feed to remote 'mine'")
    args = ap.parse_args()

    audit = get_audit(args.configs)
    optimizer = get_optimizer(args.configs, args.bets, args.bankroll)

    feed = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": {"configs": args.configs, "bets": args.bets},
        "audit": audit,
        "optimizer": optimizer,
        "community": {
            # Integration point for PropSniper community / OddsPapi consensus data.
            # Wire a fetcher here that fills `metrics`. Until then we report status
            # honestly rather than fabricating numbers.
            "status": "not_connected",
            "note": "Connect the PropSniper community / OddsPapi consensus source to populate this panel.",
            "metrics": [],
        },
    }

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "feed.json").write_text(json.dumps(feed, indent=2))
    (out_dir / "feed.js").write_text(
        "// AUTO-GENERATED by run_machine.py\nwindow.MACHINE_FEED = "
        + json.dumps(feed, indent=2) + ";\n")

    v = audit.get("verdict")
    acts = (optimizer or {}).get("summary", {}).get("actions", {})
    print(f"[{feed['generated_at']}] audit={v} cards={audit['cards']} optimizer_actions={acts}")
    print(f"wrote {out_dir/'feed.json'}")

    if args.publish:
        rel_json = str((out_dir / "feed.json").relative_to(REPO))
        rel_js = str((out_dir / "feed.js").relative_to(REPO))
        subprocess.run(["git", "-C", str(REPO), "add", rel_json, rel_js], check=True)
        msg = f"machine pulse {feed['generated_at']} — {v}"
        r = subprocess.run(["git", "-C", str(REPO), "commit", "-m", msg], capture_output=True, text=True)
        if r.returncode != 0 and "nothing to commit" in (r.stdout + r.stderr):
            print("no feed change to publish")
            return
        subprocess.run(["git", "-C", str(REPO), "push", "mine", "HEAD:main"], check=True)
        print(f"published feed to remote (commit: {msg})")


if __name__ == "__main__":
    main()
