#!/usr/bin/env python3
"""
build_data.py — run the audit engine and emit the dashboard data feed.

This is the bridge that makes the dashboard LIVE: every time you run it against
your configs, it regenerates the numbers the dashboard renders. No more static
snapshot.

Outputs two artifacts in the dashboard/ dir:
  - data.json : machine-readable, for CI / the orchestration layer / programmatic use
  - data.js   : the same payload as `window.DASHBOARD_DATA = {...}`, so index.html
                can load it via <script> with no web server and no CORS pain.

Usage:
    python dashboard/build_data.py --dir configs/sample_live      # demo
    python dashboard/build_data.py --dir live/                    # real (gitignored)
"""
from __future__ import annotations
import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
AUDIT = REPO / "audit" / "audit_configs.py"

# Map raw audit check names -> the headline cards the dashboard shows.
HEADLINE_CHECKS = {
    "self_reference": "Self-Ref Violations",
    "j_mo_no_differentiation": "Stack Collisions",
    "duplicate_id": "Duplicate Rule IDs",
    "duplicate_id_in_file": "Duplicate Rule IDs",
}


def run_audit_json(config_dir: str) -> dict:
    """Invoke the audit engine in JSON mode and return the parsed payload.

    The audit exits non-zero on findings (by design), so we don't treat a
    non-zero return code as failure here — we only fail if we can't parse JSON.
    """
    proc = subprocess.run(
        [sys.executable, str(AUDIT), "--dir", config_dir, "--format", "json"],
        capture_output=True, text=True,
    )
    if not proc.stdout.strip():
        print(proc.stderr, file=sys.stderr)
        raise SystemExit(f"audit produced no JSON (exit {proc.returncode})")
    return json.loads(proc.stdout)


def build_payload(audit: dict, config_dir: str) -> dict:
    counts = audit.get("counts_by_check", {})
    cards = {label: 0 for label in dict.fromkeys(HEADLINE_CHECKS.values())}
    for check, label in HEADLINE_CHECKS.items():
        cards[label] += counts.get(check, 0)

    return {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source_dir": config_dir,
        "verdict": audit.get("verdict"),
        "exit_code": audit.get("exit_code"),
        "summary": audit.get("summary", {}),
        "cards": cards,
        "counts_by_check": counts,
        "findings": audit.get("findings", []),
    }


def main():
    ap = argparse.ArgumentParser(description="Build the dashboard data feed from a live audit")
    ap.add_argument("--dir", required=True, help="directory of devig_*.json configs to audit")
    ap.add_argument("--out-dir", default=str(REPO / "dashboard"), help="where to write data.json/data.js")
    args = ap.parse_args()

    audit = run_audit_json(args.dir)
    payload = build_payload(audit, args.dir)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "data.json").write_text(json.dumps(payload, indent=2))
    (out_dir / "data.js").write_text(
        "// AUTO-GENERATED by build_data.py — do not edit.\n"
        "window.DASHBOARD_DATA = " + json.dumps(payload, indent=2) + ";\n"
    )

    s = payload["summary"]
    print(f"[{payload['generated_at']}] {payload['verdict']}  "
          f"files={s.get('files_checked')} rules={s.get('rules_checked')} "
          f"errors={s.get('errors')} warnings={s.get('warnings')}")
    print(f"cards: {payload['cards']}")
    print(f"wrote {out_dir/'data.json'} and {out_dir/'data.js'}")


if __name__ == "__main__":
    main()
